Customer Bulk Update API integrated
voucherifyio/voucherify-java-sdk pull request #113
Opened 2022-07-26 12:58 UTC by mabdullah12

Since the API is async, the response is void.

2022-07-27 07:50 UTC, mabdullah12 commented
Hi @tpindel
Can you review and merge it?
Thanks

2022-09-14 14:47 UTC, jkaliszuk requested changes

2022-09-15 10:54 UTC, jkaliszuk requested changes

2022-09-15 10:54 UTC, jkaliszuk commented on src/main/java/io/voucherify/client/module/CustomersModule.java
> +      if (customers.size() > 100){
API will throw error `VoucherifyError(code=400, details=Specify at most 100 customers, key=too_many_customers)` which can be caught by `VoucherifyError` exception. We don't need to check this case in code. Limits also could be changed in future.

2022-09-15 10:54 UTC, jkaliszuk commented on src/main/java/io/voucherify/client/module/CustomersModule.java
> +import io.voucherify.client.error.VoucherifyError;
Remove import according to removing if case for bulk 100+ customers.

2022-09-16 07:39 UTC, jkaliszuk approved these changes

2022-09-16 08:03 UTC, merged